name: Tests

on: [push]

jobs:
  test:

    strategy:
      fail-fast: true
      matrix:
        os: [macos-10.15, windows-latest, ubuntu-18.04]
        node-version: [12.x]
        vscode: ['1.51.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start xvfb if running Linux
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04'
      run: |
        set -e
        /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
        disown -ar
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn test --if-present
      env:
        CI: true
        DISPLAY: :10
        VSCODE: ${{ matrix.vscode }}
